version: '3'

services:

  postgres:
    image: postgres:latest
    container_name: wa-postgresql-container
    ports:
      - "${POSTGRES_BIND_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${POSTGRES_DATA}
    volumes:
      - ./.docker/postgres/data:${POSTGRES_DATA}
    networks:
      - wa-network

  node:
    container_name: wa-application-container
    image: node
    working_dir: /var/www/app
    volumes:
    - ./:/var/www/app
    command: bash -c 'npm i --silent && npm run dev'
    networks:
        - wa-network

networks:
  wa-network:
    driver: bridge
