version: '3'

services:

  postgres:
    image: postgres:latest
    container_name: wa-postgresql-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data/pgdata
    networks:
      - wa-network

  node:
    container_name: wa-application-container
    image: node
    #build:
    #  dockerfile: ./docker/Dockerfile
    #  context: .
    working_dir: /var/www/app
    volumes:
    - ./:/var/www/app
    #entrypoint: ./.docker/docker-entrypoint.sh
    command: bash -c 'npm i --silent && npm run dev'
    networks:
        - wa-network

networks:
  wa-network:
    driver: bridge